version: "3.9"

services:
  # API Service - Main service for Railway
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: tradingbot-api
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production
      - PORT=8001
      - FRONTEND_URL=${FRONTEND_URL:-https://your-app.railway.app}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    volumes:
      - api_data:/app/api/db
      - core_data:/app/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # React Client - Deploy separately or as static files
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    container_name: tradingbot-client
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=${REACT_APP_API_URL:-https://your-api.railway.app}
    restart: unless-stopped
    depends_on:
      - api

volumes:
  api_data:
    driver: local
  core_data:
    driver: local

networks:
  default:
    driver: bridge
