version: 2.1

# Define reusable jobs
jobs:
  # Install dependencies and cache them
  install-dependencies:
    docker:
      - image: cimg/node:20.19
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-deps-
      - run:
          name: Install root dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Install client dependencies
          command: cd client && yarn install --frozen-lockfile
      - run:
          name: Install API dependencies
          command: cd api && npm install
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - client/node_modules
            - api/node_modules

  # Test backend
  test-backend:
    docker:
      - image: cimg/node:20.19
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-deps-
      - run:
          name: Install root dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Install API dependencies
          command: cd api && npm install
      - run:
          name: Run backend tests
          command: yarn test:api

  # Test frontend
  test-frontend:
    docker:
      - image: cimg/node:20.19
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-deps-
      - run:
          name: Install root dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Install client dependencies
          command: cd client && yarn install --frozen-lockfile
      - run:
          name: Run frontend tests
          command: yarn test:client

  # Lint code
  lint:
    docker:
      - image: cimg/node:20.19
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-deps-
      - run:
          name: Install root dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Install client dependencies
          command: cd client && yarn install --frozen-lockfile
      - run:
          name: Install API dependencies
          command: cd api && npm install
      - run:
          name: Run linting
          command: yarn lint

  # Build Docker images
  build-images:
    docker:
      - image: cimg/node:20.19
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build API image
          command: docker build -t tradingbot-api .
      - run:
          name: Build client image
          command: docker build -t tradingbot-client -f client/Dockerfile client/

  # Deploy to Railway QA environment
  deploy-railway-qa:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      - run:
          name: Install Railway CLI
          command: npm install @railway/cli
      - run:
          name: Set Railway Environment Variables
          command: |
            echo "Setting Railway environment variables..."
            echo "RAILWAY_TOKEN is set: $([ -n "$RAILWAY_TOKEN" ] && echo "YES" || echo "NO")"
            echo "RAILWAY_PROJECT_ID is set: $([ -n "$RAILWAY_PROJECT_ID" ] && echo "YES" || echo "NO")"
            echo "RAILWAY_TOKEN length: ${#RAILWAY_TOKEN}"
            echo "RAILWAY_TOKEN starts with: ${RAILWAY_TOKEN:0:10}..."
            export RAILWAY_TOKEN=$RAILWAY_TOKEN
            export RAILWAY_PROJECT_ID=$RAILWAY_PROJECT_ID
            echo "Environment variables exported successfully"
      - run:
          name: Link Railway Project
          command: |
            echo "Linking to Railway project..."
            npx railway link --project $RAILWAY_PROJECT_ID || echo "Link failed, continuing anyway"
      - run:
          name: Deploy to Railway QA
          command: |
            echo "Deploying to Railway QA environment..."
            npx railway run --detach --verbose --service api-qa
      - run:
          name: Set QA environment variables
          command: |
            npx railway variables --set "NODE_ENV=QA" --service api-qa
            npx railway variables --set "TRADING_MODE=paper" --service api-qa
            npx railway variables --set "LOG_LEVEL=debug" --service api-qa
            npx railway variables --set "ENVIRONMENT=qa" --service api-qa
            npx railway variables --set "DEBUG=true" --service api-qa
      - run:
          name: Get QA Deployment URL
          command: |
            echo "QA Deployment URL:"
            npx railway domain

  # Deploy to Railway production environment
  deploy-railway-production:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      - run:
          name: Install Railway CLI
          command: npm install @railway/cli
      - run:
          name: Set Railway Environment Variables
          command: |
            echo "Setting Railway environment variables..."
            echo "RAILWAY_TOKEN is set: $([ -n "$RAILWAY_TOKEN" ] && echo "YES" || echo "NO")"
            echo "RAILWAY_PROJECT_ID is set: $([ -n "$RAILWAY_PROJECT_ID" ] && echo "YES" || echo "NO")"
            echo "RAILWAY_TOKEN length: ${#RAILWAY_TOKEN}"
            echo "RAILWAY_TOKEN starts with: ${RAILWAY_TOKEN:0:10}..."
            export RAILWAY_TOKEN=$RAILWAY_TOKEN
            export RAILWAY_PROJECT_ID=$RAILWAY_PROJECT_ID
            echo "Environment variables exported successfully"
      - run:
          name: Link Railway Project
          command: |
            echo "Linking to Railway project..."
            npx railway link --project $RAILWAY_PROJECT_ID || echo "Link failed, continuing anyway"
      - run:
          name: Deploy to Railway Production
          command: |
            echo "Deploying to Railway production environment..."
            echo "Current working directory: $(pwd)"
            echo "Checking Railway CLI version:"
            npx railway --version
            echo "Using railway run command (supports RAILWAY_TOKEN):"
            npx railway run --detach --verbose --service api
      - run:
          name: Set production environment variables
          command: |
            npx railway variables --set "NODE_ENV=production" --service api
            npx railway variables --set "TRADING_MODE=paper" --service api
            npx railway variables --set "LOG_LEVEL=info" --service api
            npx railway variables --set "JWT_SECRET=$JWT_SECRET" --service api
            npx railway variables --set "SESSION_SECRET=$SESSION_SECRET" --service api
      - run:
          name: Get Production Deployment URL
          command: |
            echo "Production Deployment URL:"
            npx railway domain

# Define workflows
workflows:
  # Main branch workflow - Deploy to QA after PR merge
  main:
    jobs:
      - install-dependencies
      - test-backend:
          requires:
            - install-dependencies
      - test-frontend:
          requires:
            - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - build-images:
          requires:
            - test-backend
            - test-frontend
            - lint
      - deploy-railway-qa:
          requires:
            - build-images
          context: railway-qa

  # Production release pipeline - Deploy to production on GitHub releases
  release:
    jobs:
      - install-dependencies:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - test-backend:
          requires:
            - install-dependencies
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - test-frontend:
          requires:
            - install-dependencies
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - lint:
          requires:
            - install-dependencies
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-images:
          requires:
            - test-backend
            - test-frontend
            - lint
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy-railway-production:
          requires:
            - build-images
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          context: railway-production

# Define contexts for environment variables
contexts:
  - railway-qa
  - railway-production